input {
  beats {
    port => 5044
  }
}

filter {
 
}

output {
    if [type]=="apache_access"{
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "apache_access"
            user => "elastic"
            password => "linh"
        }
    }
    else if [type]=="apache_error"{
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "apache_error"
            user => "elastic"
            password => "linh"  
        }
    }
    else if [type]=="apache_vhosts"{
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "apache_vhosts"
            user => "elastic"
            password => "linh"
        }
    }
    else{
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "other"
            user => "elastic"
            password => "linh"
        }
    }

    stdout { codec => rubydebug }
}
